# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.TextField()),
                ('time_on_page', models.IntegerField(default=0)),
                ('exit_to', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=2016)),
                ('platform', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageview', models.TextField()),
                ('session_id', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='tracking.Session')),
            ],
        ),
        migrations.AddField(
            model_name='pagedata',
            name='session_id',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='tracking.Session'),
        ),
    ]
