# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
