# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_session_ip_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='ip_addres',
            new_name='ip_address',
        ),
    ]
