# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_session_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Session'),
        ),
    ]
