# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20161204_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiondata',
            old_name='session_id',
            new_name='session',
        ),
    ]
