# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20161204_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedata',
            old_name='session_id',
            new_name='session',
        ),
    ]
