# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_session_cookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('year', models.IntegerField(default=2016)),
                ('month', models.IntegerField(default=12)),
                ('platform', models.IntegerField(choices=[(1, 'PC'), (2, 'MAC'), (3, 'IOS'), (4, 'ANDROID')])),
                ('page_1', models.IntegerField(default=0)),
                ('page_time_1', models.IntegerField(default=0)),
                ('page_pictures_1', models.IntegerField(default=0)),
                ('page_2', models.IntegerField(default=0)),
                ('page_time_2', models.IntegerField(default=0)),
                ('page_pictures_2', models.IntegerField(default=0)),
                ('page_3', models.IntegerField(default=0)),
                ('page_time_3', models.IntegerField(default=0)),
                ('page_pictures_3', models.IntegerField(default=0)),
                ('page_4', models.IntegerField(default=0)),
                ('page_time_4', models.IntegerField(default=0)),
                ('page_pictures_4', models.IntegerField(default=0)),
                ('page_5', models.IntegerField(default=0)),
                ('page_time_5', models.IntegerField(default=0)),
                ('page_pictures_5', models.IntegerField(default=0)),
                ('page_6', models.IntegerField(default=0)),
                ('page_time_6', models.IntegerField(default=0)),
                ('page_pictures_6', models.IntegerField(default=0)),
                ('page_7', models.IntegerField(default=0)),
                ('page_time_7', models.IntegerField(default=0)),
                ('page_pictures_7', models.IntegerField(default=0)),
                ('page_8', models.IntegerField(default=0)),
                ('page_time_8', models.IntegerField(default=0)),
                ('page_pictures_8', models.IntegerField(default=0)),
                ('page_9', models.IntegerField(default=0)),
                ('page_time_9', models.IntegerField(default=0)),
                ('page_pictures_9', models.IntegerField(default=0)),
                ('page_10', models.IntegerField(default=0)),
                ('page_time_10', models.IntegerField(default=0)),
                ('page_pictures_10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.TextField()),
                ('img_count', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('content_size', models.IntegerField(default=0)),
                ('lang', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('video_count', models.IntegerField(default=0)),
                ('login', models.BooleanField()),
                ('kwd_count', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('headings', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pagedata',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='country_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='session',
            name='time_zone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='pageflow',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsession',
            name='session_id',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='tracking.Session'),
        ),
    ]
