# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20161220_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 12, 20, 20, 11, 32, 404466, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
