# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_page_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedata',
            old_name='session',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='sessiondata',
            old_name='session',
            new_name='session_id',
        ),
    ]
