# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20161220_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlsession',
            name='visitor_type',
            field=models.IntegerField(default=1),
        ),
    ]
