# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_mlsession_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
