# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20161221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsession',
            name='date',
            field=models.IntegerField(default=21),
        ),
    ]
