# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20161221_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlsession',
            old_name='date',
            new_name='day',
        ),
    ]
