# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20161221_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsession',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
