# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20161221_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlsession',
            options={'ordering': ['session_id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='page',
            name='content_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mlsession',
            name='day',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='mlsession',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mlsession',
            name='year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='session',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
