# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20170114_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mlsession',
            name='day',
            field=models.IntegerField(default=17),
        ),
    ]
